#!/bin/bash
# /etc/init.d/wtfapps
# startup script for wtf applications (api+website)

# Some things that run always
touch /var/lock/wtfapps


USER=admin
WTFAPP=/home/$USER/wtfapp-mobileapp
WTFAPI=/home/$USER/wtfapp-website

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script wtfapps "
    cd $WTFAPP
    fuser $WTFAPP/start.sh || sudo -u $USER  screen -d -m  ./start.sh
    cd $WTFAPI
    fuser $WTFAPI/api.logs || sudo -u $USER ./start.sh

    ;;
  stop)
    fuser -k $WTFAPP/start.sh $WTFAPI/api.logs
    ;;
  *)
    echo "Usage: /etc/init.d/wtfapps {start|stop}"
    exit 1
    ;;
esac

exit 0
