#!/bin/bash -v
# /etc/init.d/wtfapps
# startup script for wtf applications (api+website)

# Some things that run always
touch /var/lock/wtfapps


WTFAPP=/home/wtf/wtfapp-mobileapp
WTFAPI=/home/wtf/wtfapp-website
USER=admin

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script wtfapps "
    cd $WTFAPP
    fuser $WTFAPP/nohup.out || sudo -u $USER nohup ./start.sh &

    cd WTFAPI
    fuser $WTFAPI/api.logs || sudo -u $USER ./start.sh

    ;;
  stop)
    echo "Stopping script blah"
    echo "Could do more here"
    fuser -k $WTFAPP/nohup.out $WTFAPI/api.logs
    ;;
  *)
    echo "Usage: /etc/init.d/wtfapps {start|stop}"
    exit 1
    ;;
esac

exit 0